name: Exploring Variables and Secrets

on: push
env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: patricksiandji
    IMAGE_NAME: github-actions-nginx
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker build
              run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/IMAGE_NAME:latest

            - name: Docker login
              env: 
                DOCKER_PASSWORD: test12345 
              run: docker login --username=${{ ENV.DOCKER_USERNAME }} --password=${{ env.DOCKER_PASSWORD }}

            - name: Docker publish
              run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/IMAGE_NAME:latest

    deploy_job:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            
            - name: Docker run
              run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/IMAGE_NAME:latest
            
            - name: Deploy
              run: echo deploying ...
            
            

